require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
