require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "db/seeds/**/*"
